pull_request_rules:
  - name: automatic merging of greenkeeper pulls
    conditions:
      - author=greenkeeper[bot]
      - label~=greenkeeper
    actions:
      merge:
        method: merge
        strict: true
  - name: delete merged branches
    conditions:
      - merged
      - label!=WIP
    actions:
      delete_head_branch: {}
  - name: add WIP label when WIP is in title
    conditions:
      - title~=WIP
    actions:
      comment:
        message: Please remove WIP from the title. I have set the WIP Label for you instead.
      label:
        add:
          - WIP
