language: node_js

node_js:
  - "lts/*"

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ./node_modules
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify

install:
  - npm ci

script:
  - npm run ci
